# Generated by Django 5.2.5 on 2025-09-21 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_organization_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('token_type', models.CharField(choices=[('access', "Token d'accès"), ('refresh', 'Token de rafraîchissement'), ('api', 'Token API')], default='access', max_length=20, verbose_name='Type de token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('device_info', models.JSONField(blank=True, null=True, verbose_name="Informations de l'appareil")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Token d'authentification",
                'verbose_name_plural': "Tokens d'authentification",
                'db_table': 'auth_tokens',
                'indexes': [models.Index(fields=['token'], name='auth_tokens_token_57fade_idx'), models.Index(fields=['user', 'token_type'], name='auth_tokens_user_id_6e4d12_idx'), models.Index(fields=['expires_at'], name='auth_tokens_expires_f09206_idx')],
            },
        ),
    ]
