# Generated by Django 5.2.5 on 2025-09-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('organization_type', models.CharField(choices=[('entreprise', 'Entreprise'), ('association', 'Association'), ('administration', 'Administration'), ('collectivite', 'Collectivité'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'organisation")),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organizations_organization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('member', 'Membre'), ('viewer', 'Observateur')], default='member', max_length=50, verbose_name='Rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'organisation",
                'verbose_name_plural': "Membres d'organisation",
                'db_table': 'organizations_member',
                'ordering': ['-joined_at'],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
