# Generated by Django 5.2.5 on 2025-09-19 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='organization',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name="Approuvée par l'admin"),
        ),
    ]
