# Generated by Django 5.2.5 on 2025-09-19 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_approval_date_organization_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name="Code d'invitation")),
                ('role', models.CharField(choices=[('secretaire', 'Secrétaire'), ('chef', 'Chef'), ('chef+1', 'Chef+1'), ('chef+2', 'Chef+2'), ('chef+n', 'Chef+n')], max_length=50, verbose_name='Rôle attribué')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('is_active', models.BooleanField(default=True, verbose_name='Code actif')),
                ('is_used', models.BooleanField(default=False, verbose_name='Code utilisé')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='organizations.organization', verbose_name='Organisation')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisé par')),
            ],
            options={
                'verbose_name': "Code d'invitation",
                'verbose_name_plural': "Codes d'invitation",
                'db_table': 'organizations_invitation_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
