# Generated by Django 5.2.5 on 2025-09-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('secretaire', 'Secrétaire'), ('chef', 'Chef'), ('chef+1', 'Chef+1'), ('chef+2', 'Chef+2'), ('chef+n', 'Chef+n')], default='member', max_length=50, verbose_name='Rôle'),
        ),
    ]
