# Generated by Django 5.2.5 on 2025-09-21 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationmember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du certificat', max_length=255)),
                ('subject_common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_organizational_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_country', models.CharField(blank=True, max_length=10, null=True)),
                ('subject_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('issuer_common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_country', models.CharField(blank=True, max_length=10, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=100, null=True)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('private_key_pem', models.TextField(blank=True, help_text='Clé privée au format PEM', null=True)),
                ('public_key_pem', models.TextField(blank=True, help_text='Clé publique au format PEM', null=True)),
                ('certificate_pem', models.TextField(blank=True, help_text='Certificat au format PEM', null=True)),
                ('key_usage', models.JSONField(blank=True, default=list, help_text='Usages de clé autorisés')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_certificates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='organizations.organization')),
            ],
            options={
                'verbose_name': "Certificat d'organisation",
                'verbose_name_plural': "Certificats d'organisation",
                'ordering': ['-imported_at'],
            },
        ),
    ]
