# Generated by Django 5.2.5 on 2025-09-24 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('secretaire', 'Secrétaire'), ('chef', 'Chef'), ('chef+1', 'Chef+1'), ('chef+2', 'Chef+2'), ('chef+n', 'Chef+n')], max_length=50, verbose_name='Rôle souhaité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('response_message', models.TextField(blank=True, null=True, verbose_name='Message de réponse')),
                ('invitation_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_request', to='organizations.invitationcode', verbose_name="Code d'invitation")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='organizations.organization', verbose_name='Organisation')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_membership_requests', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Demande d'adhésion",
                'verbose_name_plural': "Demandes d'adhésion",
                'db_table': 'organizations_membership_request',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
