# Generated by Django 5.2.5 on 2025-09-05 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(help_text='ID du document généré côté frontend', max_length=255)),
                ('signer_full_name', models.CharField(help_text='Nom complet de la personne qui a signé', max_length=255)),
                ('original_document', models.FileField(help_text='Document PDF original', upload_to='documents/original/')),
                ('signed_document', models.FileField(help_text='Document PDF signé', upload_to='documents/signed/')),
                ('original_filename', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('document_hash', models.TextField(help_text='Hash SHA-256 du document original')),
                ('public_key', models.TextField(help_text='Clé publique du certificat utilisé')),
                ('signature', models.TextField(help_text='Signature numérique du document')),
                ('signature_timestamp', models.DateTimeField(help_text='Timestamp de la signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size_original', models.PositiveIntegerField(help_text='Taille du fichier original en octets')),
                ('file_size_signed', models.PositiveIntegerField(help_text='Taille du fichier signé en octets')),
                ('execution_time', models.FloatField(help_text="Temps d'exécution de la signature en secondes")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature de document',
                'verbose_name_plural': 'Signatures de documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_id'], name='signatures__documen_dcb7b7_idx'), models.Index(fields=['user', 'created_at'], name='signatures__user_id_345597_idx'), models.Index(fields=['signature_timestamp'], name='signatures__signatu_0602d4_idx')],
            },
        ),
    ]
