# Generated by Django 5.2.5 on 2025-09-25 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_demandeadhesion'),
        ('signatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(help_text='ID unique du document', max_length=255, unique=True)),
                ('original_filename', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('document_title', models.CharField(help_text='Titre du document', max_length=255)),
                ('document_description', models.TextField(blank=True, help_text='Description du document')),
                ('original_document', models.FileField(help_text='Document PDF original', upload_to='documents/preparation/original/')),
                ('current_document', models.FileField(help_text='Document PDF actuel (avec signatures partielles)', upload_to='documents/preparation/current/')),
                ('final_document', models.FileField(blank=True, help_text='Document PDF final complètement signé', null=True, upload_to='documents/preparation/final/')),
                ('signature_positions', models.JSONField(default=dict, help_text='Positions des signatures sur le document')),
                ('qr_code_positions', models.JSONField(default=dict, help_text='Positions des QR codes sur le document')),
                ('elements_configuration', models.JSONField(default=dict, help_text='Configuration complète des éléments (signatures, QR codes, etc.)')),
                ('signature_workflow', models.JSONField(default=list, help_text='Ordre des signataires dans le workflow')),
                ('current_step', models.PositiveIntegerField(default=0, help_text='Étape actuelle dans le workflow (0 = préparation)')),
                ('total_steps', models.PositiveIntegerField(default=0, help_text="Nombre total d'étapes dans le workflow")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('prepared', 'Préparé par le secrétaire'), ('pending_signature', 'En attente de signature'), ('in_progress', 'En cours de signature'), ('completed', 'Signé par tous'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_at', models.DateTimeField(blank=True, help_text='Date de préparation par le secrétaire', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date de finalisation complète', null=True)),
                ('file_size_original', models.PositiveIntegerField(default=0, help_text='Taille du fichier original en octets')),
                ('preparation_notes', models.TextField(blank=True, help_text='Notes de préparation du secrétaire')),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet si applicable')),
                ('current_signer', models.ForeignKey(blank=True, help_text='Personne qui doit signer actuellement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_preparations', to='organizations.organization')),
                ('prepared_by', models.ForeignKey(help_text='Secrétaire qui a préparé le document', on_delete=django.db.models.deletion.CASCADE, related_name='prepared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préparation de document',
                'verbose_name_plural': 'Préparations de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignatureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(help_text='Ordre de cette étape dans le workflow')),
                ('signer_name', models.CharField(help_text='Nom complet du signataire', max_length=255)),
                ('signer_role', models.CharField(help_text="Rôle du signataire dans l'organisation", max_length=50)),
                ('signer_email', models.EmailField(help_text='Email du signataire', max_length=254)),
                ('signature_image', models.TextField(blank=True, help_text='Image de la signature (base64)')),
                ('signature_position', models.JSONField(default=dict, help_text='Position de la signature sur le document')),
                ('digital_signature', models.TextField(blank=True, help_text='Signature numérique cryptographique')),
                ('public_key', models.TextField(blank=True, help_text='Clé publique utilisée pour la signature')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Date et heure de signature', null=True)),
                ('signature_hash', models.TextField(blank=True, help_text='Hash de la signature')),
                ('document_hash_at_signing', models.TextField(blank=True, help_text='Hash du document au moment de la signature')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet si applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_steps', to='signatures.documentpreparation')),
                ('organization_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_steps', to='organizations.organizationmember')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étape de signature',
                'verbose_name_plural': 'Étapes de signature',
                'ordering': ['document_preparation', 'step_order'],
            },
        ),
        migrations.AddIndex(
            model_name='documentpreparation',
            index=models.Index(fields=['document_id'], name='signatures__documen_57c954_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpreparation',
            index=models.Index(fields=['organization', 'status'], name='signatures__organiz_72bc78_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpreparation',
            index=models.Index(fields=['prepared_by', 'created_at'], name='signatures__prepare_2ddb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpreparation',
            index=models.Index(fields=['current_signer', 'status'], name='signatures__current_24453e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpreparation',
            index=models.Index(fields=['status', 'created_at'], name='signatures__status_6213d5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignaturestep',
            index=models.Index(fields=['document_preparation', 'step_order'], name='signatures__documen_735821_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignaturestep',
            index=models.Index(fields=['signer', 'is_completed'], name='signatures__signer__46e81a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignaturestep',
            index=models.Index(fields=['signed_at'], name='signatures__signed__512820_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentsignaturestep',
            unique_together={('document_preparation', 'step_order')},
        ),
    ]
