# Generated by Django 5.2.5 on 2025-09-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_demandeadhesion'),
        ('signatures', '0002_documentpreparation_documentsignaturestep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignature',
            name='document_preparation',
            field=models.ForeignKey(blank=True, help_text='Préparation de document associée (pour les workflows)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_signatures', to='signatures.documentpreparation'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='is_workflow_document',
            field=models.BooleanField(default=False, help_text="Indique si ce document provient d'un workflow organisationnel"),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organisation associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_signatures', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='workflow_history',
            field=models.JSONField(default=list, help_text='Historique complet du workflow de signature'),
        ),
    ]
