# Generated by Django 5.2.5 on 2025-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_documentsignature_document_preparation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpreparation',
            name='secretary_signature_image',
            field=models.TextField(blank=True, help_text='Image de signature du secrétaire (base64)'),
        ),
    ]
