# Generated by Django 5.2.5 on 2025-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_documentpreparation_secretary_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpreparation',
            name='qr_code_positions',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='signature_positions',
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='generated_pdf',
            field=models.FileField(blank=True, help_text='PDF généré avec les éléments positionnés', null=True, upload_to='documents/preparation/generated/'),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='elements_configuration',
            field=models.JSONField(default=dict, help_text='Configuration des éléments avec structure:\n    {\n        "signature": {\n            "x": float, "y": float, "width": float, "height": float, "page": int\n        },\n        "qr_code": {\n            "x": float, "y": float, "size": str ("small"|"medium"|"large"), "page": int\n        }\n    }'),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='secretary_signature_image',
            field=models.ImageField(blank=True, help_text='Image de signature du secrétaire', null=True, upload_to='signatures/secretary/'),
        ),
    ]
