# Generated by Django 5.2.5 on 2025-09-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0005_remove_documentpreparation_qr_code_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_page',
            field=models.PositiveIntegerField(default=1, help_text='Page du QR code'),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Taille du QR code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_x',
            field=models.FloatField(blank=True, help_text='Position X du QR code', null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_y',
            field=models.FloatField(blank=True, help_text='Position Y du QR code', null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_height',
            field=models.FloatField(blank=True, help_text='Hauteur de la signature', null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_page',
            field=models.PositiveIntegerField(default=1, help_text='Page de la signature'),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_width',
            field=models.FloatField(blank=True, help_text='Largeur de la signature', null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_x',
            field=models.FloatField(blank=True, help_text='Position X de la signature', null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_y',
            field=models.FloatField(blank=True, help_text='Position Y de la signature', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='elements_configuration',
            field=models.JSONField(default=dict, help_text='Configuration complète des éléments (JSON)'),
        ),
    ]
