# Generated by Django 5.2.5 on 2025-09-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0006_documentpreparation_qr_code_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_mode',
            field=models.CharField(blank=True, choices=[('all', 'All Pages'), ('current', 'Current Page'), ('custom', 'Custom Pages'), ('individual', 'Individual Pages')], help_text="Mode d'application du QR code", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_pages',
            field=models.JSONField(blank=True, help_text='Configuration des pages pour le QR code (all, current, [1,2,3], etc.)', null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_mode',
            field=models.CharField(blank=True, choices=[('all', 'All Pages'), ('current', 'Current Page'), ('custom', 'Custom Pages'), ('individual', 'Individual Pages')], help_text="Mode d'application de la signature", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_pages',
            field=models.JSONField(blank=True, help_text='Configuration des pages pour la signature (all, current, [1,2,3], etc.)', null=True),
        ),
    ]
