# Generated by Django 5.2.5 on 2025-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0007_documentpreparation_qr_code_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpreparation',
            name='qr_code_page',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='signature_page',
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_positions',
            field=models.JSONField(blank=True, help_text='Positions spécifiques par page: {default: {x, y}, 1: {x, y}, 2: {x, y}}', null=True),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_positions',
            field=models.JSONField(blank=True, help_text='Positions spécifiques par page: {default: {x, y}, 1: {x, y}, 2: {x, y}}', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='qr_code_pages',
            field=models.JSONField(blank=True, help_text="Pages où appliquer le QR code ('all', [1,2,3], etc.)", null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='qr_code_x',
            field=models.FloatField(blank=True, help_text='Position X du QR code en pourcentage', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='qr_code_y',
            field=models.FloatField(blank=True, help_text='Position Y du QR code en pourcentage', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='signature_pages',
            field=models.JSONField(blank=True, help_text="Pages où appliquer la signature ('all', [1,2,3], etc.)", null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='signature_x',
            field=models.FloatField(blank=True, help_text='Position X de la signature en pourcentage', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='signature_y',
            field=models.FloatField(blank=True, help_text='Position Y de la signature en pourcentage', null=True),
        ),
    ]
