# Generated by Django 5.2.5 on 2025-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0008_remove_documentpreparation_qr_code_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpreparation',
            name='qr_code_mode',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='qr_code_pages',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='qr_code_positions',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='signature_mode',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='signature_pages',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='signature_positions',
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='qr_code_page',
            field=models.PositiveIntegerField(default=1, help_text='Page du QR code'),
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='signature_page',
            field=models.PositiveIntegerField(default=1, help_text='Page de la signature'),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='qr_code_x',
            field=models.FloatField(blank=True, help_text='Position X du QR code', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='qr_code_y',
            field=models.FloatField(blank=True, help_text='Position Y du QR code', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='signature_x',
            field=models.FloatField(blank=True, help_text='Position X de la signature', null=True),
        ),
        migrations.AlterField(
            model_name='documentpreparation',
            name='signature_y',
            field=models.FloatField(blank=True, help_text='Position Y de la signature', null=True),
        ),
    ]
