# Generated by Django 5.2.5 on 2025-09-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0009_add_missing_page_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpreparation',
            name='page_mode',
            field=models.CharField(choices=[('all', 'Toutes les pages'), ('current', 'Page actuelle'), ('custom', 'Pages personnalisées'), ('individual', 'Positions individuelles')], default='all', help_text="Mode d'application des éléments", max_length=20),
        ),
    ]
