# Generated by Django 5.2.5 on 2025-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0010_add_page_mode_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpreparation',
            name='qr_code_page',
        ),
        migrations.RemoveField(
            model_name='documentpreparation',
            name='signature_page',
        ),
        migrations.AddField(
            model_name='documentpreparation',
            name='applied_pages',
            field=models.JSONField(default=list, help_text='Pages où les éléments sont appliqués (selon le mode)'),
        ),
    ]
